### ISSUE TITLE
[Question] Where is the C++ source for the decoders ?

### ISSUE THREAD

**Issue by Paulo-D2000** [Lcrypto/LDPC-Iterative-Bit-Flipping-family-decoders#1]
Hi! This seems like one amazing project but where are the c++ files for the decoders ? Thanks :)

**Comment by Lcrypto** [comment]
Hello Paulo! 
It's contained in header file, it strange solution but I decided not to change the original source files of the Fernando Pujaico Rivera project:
Simula.h for example contain dec functions 
"
void SH_bitflipping(Vector *Vb,const Vector *r1,Linha **LinhaPadrao,unsigned short NumLP,float p)
{
...
}
"

With BR, Vasiliy

**Comment by Lcrypto** [comment]
Just check https://github.com/Lcrypto/LDPC-Iterative-Bit-Flipping-family-decoders/blob/main/bf-tests-awgn-egldpc_0.2.orig/bf-tests-awgn-egldpc-0.2/src/extras/simula.h
